### ISSUE TITLE
move cursor to previous/next request

### ISSUE THREAD

**Issue by teto** [rest-nvim/rest.nvim#136]
I have a .http file with several request:
```
A
----
B
---
C
```

My usual workflow is to run A -> B -> C (yet I dont want to automate that, I want to keep it manual since I sometimes run C -> A etc). What could be fun is to move the cursor to the next request after running the request. I could create a mapping that run the request and then search for `-----` but I would like to do it the treesitter way. I have to look at the treesitter grammar to do it.

**Comment by NTBBloodbath** [comment]
I've been thinking about changing how things like variables (that aren't part of RFC standard followed by rest.nvim) work and better adopting RFC 2616.

If those hyphens as a separator aren't part of RFC 2616 and you plan to use treesitter for this feature, we could just jump from request to request by looking for `request` nodes and get their position in buffer so we can move cursor with `nvim_win_set_cursor(window, pos)`.

---

Note to myself: maybe I should refactor the internal buffer parser to use treesitter instead of manually scanning the entire buffer

**Comment by boltlessengineer** [comment]
Closing this issue.
rest.nvim now uses treesitter to parse each requests and support `###` delimiter to indicate each request sections.
