### ISSUE TITLE
Add support for *.py files

### ISSUE THREAD

**Issue by kobzar** [rest-nvim/rest.nvim#269]
HI. Thanks for this plugin for first. 
really its good for simple tests.
But could you add run support for different file types? 
For example its no cool to goto another tab for run query every time
It will be nice to add comment line before function and run it directly
Something like this 

.../test.py
```python
# GET http://127.0.0.1/?name=User
@app.get("/gq/")
async def get_value(word: str):
    ic(word)
    return word
```

At this time i se the error
"No request found...."

**Comment by boltlessengineer** [comment]
This seems too complicated & fragile to include as builtin feature.
Currently `Rest run` only runs on `.http` file because it uses tree-sitter parser attached to that buffer.
We can parse the raw comment content as a string with tree-sitter, but some features (e.g. in-place variables) are only available when we use tree-sitter parser attached to real buffer.
