### ISSUE TITLE
I am unable to install rest.nvim

### ISSUE THREAD

**Issue by Muizzyranking** [rest-nvim/rest.nvim#397]
I am somewhat new to neovim and I am trying to install rocks nvim and I am getting this error
    ○ rest.nvim  http 
        `lua` version `5.1` needed, but found `Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio`
        `lua5.1` or `lua` or `lua-5.1` version `5.1` not installed

        This plugin requires `luarocks`. Try one of the following:
         - fix your `luarocks` installation
         - enable `hererocks` with `opts.rocks.hererocks = true`
         - disable `luarocks` support completely with `opts.rocks.enabled = false`
I have luarocks installed but i do not know if i have to uninstall the current version of lua and intall the supported version.

**Comment by NTBBloodbath** [comment]
Hi,

By default luarocks is compiled using Lua 5.4, lazy's support is a little tricky due to the implementation that has been made (+ the fact about luarocks that I mentioned before), so I would recommend activating hererocks support in your `lazy.nvim` configuration as specified in the error message.

The other option would be to uninstall your system's luarocks, install Lua 5.1 on your system and compile luarocks with that version manually which is a very fast, but tedious process so I would go with the first option to fix this issue. If after activating hererocks support in lazy.nvim you still have problems in this regard, I think the best thing would be to see the open and closed issues in its repository to see if anyone has had similar problems before opening a new issue.

Cheers

**Comment by Muizzyranking** [comment]
I am unable to get this to work, I have enabled luarocks in lazy, I do not know if I got the config right. But I am still having lua version error. Thank you for taking your time to respond but I think I will try kulala or just keep using curl. Thank you once again, appreciate your response.
