### ISSUE TITLE
Feature: set curl opts globally/per request

### ISSUE THREAD

**Issue by sheimer** [rest-nvim/rest.nvim#435]
### Issues

- [X] I have checked [existing issues](https://github.com/rest-nvim/rest.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I have a route which sends a csv file with content-encoding gzip.

To be able to see the result in neovim, I have to set the `--compressed` arg on the curl command. I found no way to do so but changing the args in `lua/rest-nvim/client/curl/cli.lua`.

Maybe there is a way to allow args to be passed to curl in general? Or set --compressed, if Accept-Encoding header is set and contains gzip?

**Comment by boltlessengineer** [comment]
I’m thinking of providing `meta` field for `rest.Request` type.
So users can make `User RestRequestPre` autocommand to update the request metadata before running a request
and clients like `curl` can use that metadata on request.

Introducing additional document comment (e.g. `# @curl-args --compressed`) might make things easier, but I’m bit skeptical to introduce too much new specs on top of other plugins from intellij/vscode)

Adding `--compressed` argument automatically based on header type sounds like a good idea.

Would this fit your needs?
Also please tell me if you are willing to make a PR. If not, I will do it but it might take some time due to personal schedules.

**Comment by sheimer** [comment]
I will try if I can do a PR...time might be a problem, and maybe my capabilities as well ^^ We will see :)

**Comment by boltlessengineer** [comment]
#439 is merged now. manually closing the issue
